---
repository:
  path: github.com/timonwong/uwsgi_exporter
go:
  version: 1.20
  cgo: false
build:
  binaries:
    - name: uwsgi_exporter
      path: ./cmd/uwsgi_exporter
  flags: -a -tags 'netgo'
  ldflags: |
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
  files:
    - LICENSE
